name: tokenlab_challenge
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  rxdart: ^0.24.1
  enum_to_string: ^1.0.9
  fluro: ^1.6.3
  json_serializable: ^3.4.1
  flutter_localizations:
    sdk: flutter
  intl: 0.16.1
  dio: ^3.0.10
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner: ^1.10.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/top-20.png

flutter_intl:
  main_locale: en_US
  enabled: true